# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog Ramon Esteban
permalink: none
email: wantedforcode@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a 
  prominent sidebar with uncomplicated content
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ramonesteban78.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter: ramonesteban78
github: ramonesteban78
linkedin: ramonesteban78

#paginate: 2
#paginate_path: "/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-auto-image
exclude:
  - Gemfile
  - Gemfile.lock

author-image: /public/clint.jpg